declare namespace server{

  export interface WeatherForecast {
    date:         Date;
    temperatureC: number;
    temperatureF: number;
    summary:      string;
  }
}

// Generated by https://quicktype.io


